version: '3'
services:

  app:
    image: dekribellyliu/captcha-form:1.0
    ports:
      - 80:80
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    networks:
      - app

networks:
  app: